M48
; DRILL file {KiCad 8.0.1-rc2} date 2025-04-21T15:53:20+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-21T15:53:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1-rc2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X4.4285Y-3.4823
T2
X4.4285Y-3.7972
M30
